### ISSUE TITLE
v1.1.0 breaks HTTP GET

### ISSUE THREAD

**Issue by kjetilpp** [bitfocus/companion-module-generic-http#14]
Hello. 
After update to v1.1.0 all of my HTTP GET requests stopped working, downgraded to v1.0.8 and all are working fine. 

Example a GET request to Node-RED with url http://10.1.0.184:1880/endpoint/all-off

Companion 2.2.0 (2.2.0-a022e035-3605) on Pi4

**Comment by krocheck** [comment]
Do you use the header field for that GET?

**Comment by kjetilpp** [comment]
No. Only URI--
----
Kjetil P. Pedersen

**Comment by krocheck** [comment]
@estilles https://github.com/bitfocus/companion-module-generic-http/blob/a56bd0e90b897fdbf2cec00509ed4b0a6957a2a1/index.js#L180 this should check ‘restCmd’?

**Comment by estilles** [comment]
Checking ...

**Comment by estilles** [comment]
> @estilles
> 
> https://github.com/bitfocus/companion-module-generic-http/blob/a56bd0e90b897fdbf2cec00509ed4b0a6957a2a1/index.js#L180
> 
> this should check ‘restCmd’?

Yes. Submitting PR to fix.
