### ISSUE TITLE
v1.1.1 with GET "Cannot read property 'trim' of undefined"

### ISSUE THREAD

**Issue by cprima** [bitfocus/companion-module-generic-http#16]
Hi,

unfortunately I am getting errors in the Companion log:
> Error executing action: Cannot read property 'trim' of undefined

I renamed my companion folder on my Raspberry Pi and did a fresh installation as per
https://github.com/bitfocus/companion/wiki/Manual-Install-on-Raspberry-Pi

Tried several settings like empty baseurl, bogus header input and such, but could not get the module to execute.

Is it only my installation or can this be reproduced?

**Maybe the GET action triggers line 152 (GET has no body)?**
`	if (action.options.body.trim() !== '') {`

Here a minimal example:
```    "instances": {
        "qhXcokpuL": {
            "instance_type": "generic-http",
            "product": "HTTP Requests",
            "label": "http",
            "enabled": true,
            "prefix": "http://server.url/path/"
        }
    },
    "actions": {
        "1": [],
        "2": [{
                "id": "kJLp_CbXV",
                "label": "qhXcokpuL:get",
                "instance": "qhXcokpuL",
                "action": "get",
                "options": {
                    "url": "http://10.38.20.21:5000/usbgadget/command/userid",
                    "header": ""
                },
                "delay": 0
            }
        ],```

[sarmum_page 96_20211116-1308.companionconfig.txt](https://github.com/bitfocus/companion-module-generic-http/files/7546132/sarmum_page.96_20211116-1308.companionconfig.txt)

**Comment by krocheck** [comment]
@estilles

**Comment by estilles** [comment]
Checking ...

**Comment by estilles** [comment]
Yeah ... I'm missing the optional chaining question mark.

**Comment by estilles** [comment]
@krocheck / @cprima ... Thanks for reporting! PR submitted.

**Comment by cprima** [comment]
I can confirm that the issue is fixed (git pull'ed and yarn-update'd)

**Comment by estilles** [comment]
Thanks @cprima! Always appreciate your help.
