### ISSUE TITLE
When using the GET command on a button, I can not find a way to save the response to a Variable. 

### ISSUE THREAD

**Issue by harrovandoorn** [bitfocus/companion-module-generic-http#23]
When using the http Generic connection in my Companion I am able to fire a GET command to my internal Home Domotica (Homey) system and this way starting/ stopping some things like lights, blinds etc.

Now I also want to be able to retrieve data from my domotica system, to display on the Companion buttons. In example when I use a API-URL in the browser, it will give me a answer like "Status is Green". Or " Light is on" . I then want to be able to save this response, in a Companion Variable to use later on.

When using the GET command on a button, I can not find a way to save the response to a Variable. How would I go about that ?

**Comment by JeffreyDavidsz** [comment]
Hi Harro, this module is only intended to send, not to receive. For that you would need to create a module for the equipment you want to use.

**Comment by abebeos** [comment]
@harrovandoorn , @JeffreyDavidsz , this looks like what is suggested within #24 (which has a bounty on it)
