### ISSUE TITLE
Add the ability ability to set custom variable values with an HTTP request

### ISSUE THREAD

**Issue by amcchord** [bitfocus/companion-module-generic-http#24]
Add the ability for a GET request to save the response from the remote server to a custom variable. 

These variables can be used with other modules in the companion ecosystem. 

One example might sending a GET request to get the name of file to play next from a custom web app. Then store this name in a variable and use it with the HyperDeck module to play that file.

**Comment by ffxisf** [comment]
use redis server save custom variable.

**Comment by retog** [comment]
here you go:
> let myCustomVariable = await (await fetch("https://github.com")).text()

**Comment by amcchord** [comment]
What? I think you are missing it. This would be added to the companion UI needs to be updated and would be great if I could specify a companion custom variable for the result of this call to be stored in. 

<img width="613" alt="Screen Shot 2022-02-01 at 4 06 32 PM" src="https://user-images.githubusercontent.com/9466882/152051506-87be5f7c-eab6-4e7b-b8d6-17944b508983.png">

**Comment by abebeos** [comment]
(draft, the comment will be updated)

## Requirements

**Comment by abebeos** [comment]
@amcchord, as you describe it, this needs to work within one browser (e.g. multiple client modules share variables within one browser). Is this correct?

**Comment by amcchord** [comment]
yeah it needs to be part of the companion system the way the other valuables end up there. It's less about being in the browser and more about being part the system so you use the variables when working with other modules.

**Comment by amcchord** [comment]
Companion already supports variables and custom variables. You can create them in the UI and assign them a value there. The goal of this would be for a variable created in the companion UI to have its value updated by the result of companion making an HTTP GET request.

**Comment by abebeos** [comment]
I understand. Can you suggest a dev-system-setup (ideally one that does not need hardware)?

The document https://github.com/bitfocus/companion/wiki/Module-Development is far too verbose for experienced devs, anything more compact available (or a development-starter repo)?

Other than this, I do not see any problems after reading a little bit around. Nice system!

**Comment by abebeos** [comment]
@amcchord, please confirm:

- the new functionality should be provided within `generic-http` (this repo)
- `matchManager` within [your comment above](https://github.com/bitfocus/companion-module-generic-http/issues/24#issuecomment-1027288038) is your own module based on `generic-http`

(note that I update [my comment](https://github.com/bitfocus/companion-module-generic-http/issues/24#issuecomment-1028062341) whilst progressing)

**Comment by abebeos** [comment]
Ignore last comment, all good.

**Comment by mertmit** [comment]
I added the requested feature in my pull request (https://github.com/bitfocus/companion-module-generic-http/pull/25).

**Comment by amcchord** [comment]
I guess the best way to think about this would be that you can add custom variables are part of the HTTP module and they would be assigned based on the response from a get request. If you are looking for examples of custom variables check out the Spotify Module. 


![Screen Shot 2022-02-10 at 12 37 25 PM](https://user-images.githubusercontent.com/9466882/153464514-5f551523-e584-47d9-9021-0c9b760e514f.png)

**Comment by lazaridiscom** [comment]
@amcchord , do you expect a fully automated/generic processing, or is it fine to create the rest-requests manually for each variable to assign?

As a sidenote: please note that there is a problem with bounties and open collaboration. As long as only one developer works on the bounty, everything is fine. When a 2nd (or more) jumps in (hi there @mertmit), things can become complicated. As an example, one developer executes a requirements-analysis in public, a second developer codes in parallel and claims the bounty in the end.

In any way, I'll continue my work for now and will most possibly publish my results over the weekend.

(@mertmit , if you're close to the team and get directions/requirements from there, please let me know so I can decide better if I continue with this)

**Comment by mertmit** [comment]
@amcchord I used internal variables to save HTTP response -which you can use as $(internal:custom_VARNAME)- but I think you want to parse data you receive so you can assign more variables from one request. It is important to know what type of data you want to use as it is different to parse (JSON, raw HTML etc. or even if you want seperate options for both). So can you give further info on data you want to get.

(@abebeos I am not related with the team.)

**Comment by abebeos** [comment]
@amcchord , please take a look at #27. If you're on the teams slack, you may want to post a quick ping to get more of the core-devs attention.

**Comment by mertmit** [comment]
![Settings](https://user-images.githubusercontent.com/59797957/153563428-37baffa3-d07d-4595-a2be-fe35ba031b66.png)
![Button1-1](https://user-images.githubusercontent.com/59797957/153563429-6fe3de4e-920e-4cb8-bd94-18101069428b.png)
![Button1-2](https://user-images.githubusercontent.com/59797957/153563430-85b3c5f5-8585-4907-96d1-3f31636daeee.png)
![Emulation1](https://user-images.githubusercontent.com/59797957/153563433-c1e2a2bf-a90a-47fb-9d16-d8d55e1aa465.png)
![Emulation2](https://user-images.githubusercontent.com/59797957/153563434-3a2f327f-bbc5-4f80-8f29-cf091e0df21e.png)
![Other-Buttons](https://user-images.githubusercontent.com/59797957/153563424-4811bbfc-4cb8-43d1-a2dc-81fef243e114.png)

@amcchord This is an example result after last push, I sticked to main repository and extended it so this PR not effect main function of the repository. You can assign internal variables and use them on other modules as intended.

**Comment by Julusian** [comment]
I've assigned the issues/prs related to this to myself, as I intend to properly read through this and figure out the correct approach over the weekend

**Comment by abebeos** [comment]
@amcchord , I've moved all my relevant information re this task to issue #27. You can already start testing, though I would wait until more coordination happens with @Julusian.

You can expect to have a flexible workable result until the announced date (15th Feb.). Getting the results into this repository could take a few days more (depending on companion core-team).

**Comment by abebeos** [comment]
@amcchord , you can test the result now, https://github.com/bitfocus/companion-module-generic-http/pull/28 contains a simple test-sequence with screenshots.

**Comment by abebeos** [comment]
@amcchord , you need to 'accept` my claim on bountysource, otherwise the payout takes 2 weeks.

**Comment by abebeos** [comment]
All good, thank you!

**Comment by abebeos** [comment]
@amcchord , @JeffreyDavidsz , there is a problem with bountysource, nearly 2 weeks and they still have not send the escrowed amount via paypal, see:

https://github.com/abebeos/main/issues/2

I'm afraid I'll need to ask you to go through further trouble and file a complaint @ paypal, so you can transfer me the amount directly once it is refunded from paypal.

**Comment by JeffreyDavidsz** [comment]
@abebeos as I read it, the solution is near. Please do not pollute this channel on external matters. I would advise not to go through other payment options until its absolutely clear Bountysource is failing. Then Bountysource should pay back to @amcchord first before he will transfer it again against something else. But again, this has noting to do with Companion, so please keep it out here.

**Comment by abebeos** [comment]
> Please do not pollute this channel on external matters.

"pollute"? "external"?

I do not know where this is coming from. I naturally contact the bounty-issuer here (within the issue), and I feel at this point very(!) uncomfortable by your reaction.

"as I read it, the solution is near" - no, it's not, as bountysource says "soon" "tomorrow" "already payed" since nearly 2 weeks. It is not the first time I've problems (though never that long), and I'm not the only one (others seem to be unpaid since months).

> I would advise not to go through other payment options until its absolutely clear Bountysource is failing.

2 weeks for a paypal transfer *IS* actually failing. I was just preparing @amcchord that steps could become necessary (gladly paypal as protection-mechanisms), but I wanted to wait the 3 days anyways.

**Comment by abebeos** [comment]
Got the cash-out, a simple paypal-transaction, made by bountysource after 17(!) days.

(@JeffreyDavidsz , I'll delete my above non-relevant comments, as I do usually always, even with in-topic comments)
