### ISSUE TITLE
Should be able to send request when releasing button

### ISSUE THREAD

**Issue by EnergeticStick** [bitfocus/companion-module-generic-http#33]
You should be able to send two requests with one button.  One on button press, and another on button release, for devices that need a stop command.

**Comment by josephdadams** [comment]
Good news! You can! Just add the stop command on the “release”/“up” action in the UI.

**Comment by EnergeticStick** [comment]
Yep...just figured it out a few minutes before you replied, was waiting to get home to delete this issue.  I've only ever used the PTZ VISCA module so I just thought the "Release Action" was specific to that module, I didn't realize it was a generic button setting.  So sorry for wasting your time. 🤦‍♂️

**Comment by josephdadams** [comment]
No problem!
