### ISSUE TITLE
Expose http response as variable

### ISSUE THREAD

**Issue by gavalierm** [bitfocus/companion-module-generic-http#34]
Why this modul do not accept any response? It this is generic http modul how i can achieve receivin data from http (json) and do some stuff like change color by value in response?

EDIT: I found commit 4 days ago that accept response and add abiity to use image from URL. There is little step to add feedback to change color/bg or expose json variable from response body json.

**Comment by Julusian** [comment]
It already is possible to save the result to a custom-variable. The `JSON Response Data Variable` option

![image](https://user-images.githubusercontent.com/1327476/216784737-3ea0777c-842d-4082-aaa6-4d7cd85eb7df.png)

**Comment by David-COUDRAY** [comment]
Hi team,

Yes, but only possible to HTTP GET request.
Why we don't set a custom variable on HTTP PUT request ?
