### ISSUE TITLE
Updating button background thumbnails (for PTZ presets etc)

### ISSUE THREAD

**Issue by premultiply** [bitfocus/companion-module-generic-http#40]
### Is this a feature relevant to companion itself, and not a module?

- [X] I believe this to be a feature for companion, not a module

### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the feature

After working a while with companion as preset shotbox in live situations with multiple ptz cameras I thought about a way to show visual preset information on the stream deck buttons. This would make operators live much easier because you do not have to remind ordinary preset numbers from multiple cameras for visual scenes. This sometimes feels like playing memory card game with a child... you simply get lost.

The cameras that I use (Panasonic AW-UE150) save a thumbnail at every time a preset is saved or updated.
These thumbnails are shown on the camera config web UI for every preset.
They can be fetched via HTTP API directly from the camera (`http://CAMERAIP/cgi-bin/get_preset_thumbnail?preset_number=X` on Panasonic AW-UE150 and others).

The request is to show and automatically update background thumbnails on preset recall buttons each time a preset is saved (or overwritten or deleted). This wont be limited to cameras presets. Even other sources like video mixer scenes, cg titles, crossbar inputs may be a target for this feature.

Part 1 may be a general infrastructure (trigger?) for fetching background thumbnails from devices, scale/convert them, save them on disk and show/update on button background.
Part 2 may be the device specific integration (panasonic ptz module in my case).

### Usecases

* PTZ camera presets
* Video inputs / outputs from routers or mixers
* Scenes or mediapool from mixer like OBS, ATEM vMix, CasparCG etc.
* CG, Clip or image playout server

**Comment by peternewman** [comment]
There's an image from URL feedback added since you mentioned this, will that do what you need?
https://github.com/bitfocus/companion-module-generic-http/commit/2bf5e8a35373281bc6dabcd9740e50e6d74e15ea

**Comment by premultiply** [comment]
Yes, already implemented in https://github.com/bitfocus/companion-module-panasonic-cameras

Will be available soon.

**Comment by peternewman** [comment]
But there is also a means of doing similar things within the generic HTTP module too...
