### ISSUE TITLE
Module crashes when importing a config

### ISSUE THREAD

**Issue by tomhillmeyer** [bitfocus/companion-module-generic-http#42]
I'm running 3.0.0-rc2. I have a generic HTTP module in my Companion config. The module actually had no settings to it, as I was using a different URL in each button. I exported that config file, then wiped my Companion instance to make a different confg.

When I went back to my previous config with the HTTP module in it, the module says it "Crashed" and no amount of restarting my computer, Companion, or the module helped. What's worse is at the button level it doesn't let me see what parameters I had the buttons do, so I can't even add a new generic HTTP module and plug in the old parameters.

Adding a new generic HTTP module works, so it's not my computer or setup. It appears that the export/import process breaks this module somewhere.

**Comment by Julusian** [comment]
This is also fixed in the beta builds and will be included in the next stable release when that happens
