### ISSUE TITLE
error message incorrect

### ISSUE THREAD

**Issue by alex-Arc** [bitfocus/companion-module-generic-http#45]
when a `post` gets a 400 back from the serve the log shows this
![image](https://github.com/bitfocus/companion-module-generic-http/assets/19875125/472bda95-fc8d-4fe6-be82-b0b5ce65de1b)
should it not read `HTTP POST Request failed (Response code 400 (Bad Request))`

**Comment by josephdadams** [comment]
This was fixed in a PR just now
