### ISSUE TITLE
Ignore Non_2XX_3XX_Response ?

### ISSUE THREAD

**Issue by Coupe70** [bitfocus/companion-module-generic-http#46]
In some cases I get a Non_2XX_3XX_Response from a GET request.
I KNOW this and I can't do anything about it, but this response always gives me an error and disables the http module. 
Is there any way to handle this or just ignore this error to keep the http module alive?

**Comment by istnv** [comment]
I don't think errors disable the module, the message just sticks until the next request.
I have one setup where I can press a button, and if the program is not running, always shows an error. Start the program and press another command, the error goes away.

**Comment by mark-epstein** [comment]
In the picture you posted on FB, the module is not disabled.

If something does disable it, there's a built-in action that you could use to enable it. You can add that action to a button or pretty much anything else by using the triggers function.

**Comment by Coupe70** [comment]
Thanks for your answers!
I actually didn't mean disabled in terms of "switched off", more like "stops working".
But last week was crazy and I might be completely wrong.
I'll check again on monday...

**Comment by Coupe70** [comment]
Guys, you were absolutely right!
Thanks for pointing out.
