### ISSUE TITLE
Cannot use this for x-callback calls

### ISSUE THREAD

**Issue by jgclark** [bitfocus/companion-module-generic-http#51]
I realise this module has HTTP in the title ... but I was hoping to find a way to trigger x-callbacks with other protocols than http(s).

My particular use case is for NotePlan app which has many functions that can be triggered this way.
e.g. `noteplan://x-callback-url/runPlugin?pluginID=jgclark.Dashboard&command=show%20dashboard`

Apologies if another module covers this, but if so its not obvious from the name.

**Comment by JeLuF** [comment]
According to the [noteplan documentation](https://help.noteplan.co/article/49-x-callback-url-scheme#testing), you can access noteplan URLs from the command line using the "open" command. So you should be able to use the 'internal: System: Run shell path (local)' action, using the path:
```
open "noteplan://x-callback-url/runPlugin?pluginID=jgclark.Dashboard&command=show%20dashboard"
```

Not having a Mac, I couldn't test this myself.

**Comment by jgclark** [comment]
You're a ⭐️ @JeLuF. Thanks for figuring out that successful alternative.
