### ISSUE TITLE
Can't GET http://127.0.0.1:8000/buttons

### ISSUE THREAD

**Issue by jgclark** [bitfocus/companion-module-generic-http#52]
Ironically, I can't get this to launch Companion's own web GUI.
i.e. `http://127.0.0.1:8000/buttons` as a `HTTP: GET` doesn't launch anything, and doesn't show anything in the logs either (apart from "Button ... pressed").
I confirm that I manually do `open "http://127.0.0.1:8000/buttons"` at the command line it has the intended effect.

macOS 13.6.2 / Companion 3.3.0-6693

**Comment by Julusian** [comment]
That is expected. This module will be making the request successfully, but making a http request does not spawn a browser window.
For that you should use the internal action to run a shell command of `open "http://127.0.0.1:8000/buttons"`

**Comment by jgclark** [comment]
OK. Could I humbly suggest you then add this to the documentation? This is the module labelled http, and at least to this programmer, the distinction isn't obvious. Thanks.
