### ISSUE TITLE
Using HTTP generic as workaround for PTZJoy module

### ISSUE THREAD

**Issue by GuideOTA** [bitfocus/companion-module-generic-http#55]
The set preset command in the PTZJoy module is broken so I am using HTTP generic to send the correct command as a workaround.
I have an Idea of how to fix the module but I am far from an expert on any of this.

**Comment by GuideOTA** [comment]
upon further investigation there is a working save current preset command in the module, but the save preset command will still not work

**Comment by Julusian** [comment]
I think you would be better off asking on slack or facebook for help with this.

Any of the maintainers here will likely have no idea how the ptzjoy module does http, so can't provide any help with trying to replicate that.
