### ISSUE TITLE
Is Custom Variable: Set from a stored JSONresult via a JSONpath expression gone?

### ISSUE THREAD

**Issue by roverradio** [bitfocus/companion-module-generic-http#56]
I'm trying to parse a JSON response from a GET, But I do not see Custom Variable: Set from a stored JSONresult via a JSONpath expression available in any of my companion installations (3.3 through experimental).

Is this still in there? A new way to do the same?

Thanks

**Comment by Julusian** [comment]
This got combined into the expression syntax, use `internal: Custom Variable: Set with expression` to achieve the same

Perhaps something like:
![image](https://github.com/bitfocus/companion-module-generic-http/assets/1327476/b65cf642-18b3-43e8-a7fa-b243270bdc7d)
