### ISSUE TITLE
execute javascript in returned html

### ISSUE THREAD

**Issue by fbosman** [bitfocus/companion-module-generic-http#67]
I need to parse a complete html page to find a state for a button. However, this functions does not execute the javascript on this html page.
Is there a way to have it executed and so retrieve the complete html page?

**Comment by jswalden** [comment]
If you functionally want to execute pages as if in a browser, you probably are going to have to actually drive a web browser to do it.  Theoretically, a generic module to do that, using something like [WebDriver](https://www.selenium.dev/documentation/webdriver/) driving an actual browser, might be the right approach.  Definitely, tho, it's not something to have in a generic HTTP interactions module.

**Comment by Julusian** [comment]
I agree, supporting this would require either interacting with a webbrowser on the machine, or for the module to package one (which will likely double the install size of companion).
While I see value in it, that is out of scope for this module.
