### ISSUE TITLE
Enable fetching presets over HTTP

### ISSUE THREAD

**Issue by astellingwerf** [bitfocus/companion-module-generic-http#8]
It'd be great if this module could also (optionally) GET an endpoint to fetch presets. It would of course be up to the custom integration to provide those, but it could greatly simplify the work flow of setting up the keys if the implementation bothered to do so.

**Comment by JeffreyDavidsz** [comment]
I'm sorry I don't understand your question. Can you give an example?

**Comment by astellingwerf** [comment]
The `InstanceSkel` has a function `setPresetDefinitions` that can set presets for a plugin. It's input parameter for it could be hardcoded, but it's "just code", so the input could be dynamic as well. I'd want to specify an endpoint that the plugin can invoke, where it can get a set of definitions of the applicable presets.

**Comment by JeffreyDavidsz** [comment]
I'm closing this. please request a new module for your product where you -or someone else- can add this functionality. The generic modules are for simple testing only
